CREATE TABLE HOUSE_MEMBER_STORE (
  MEMBER_STORE_ID VARCHAR(15) NOT NULL,
  MEMBER_STORE_NAME_JP VARCHAR(255),
  MEMBER_STORE_NAME_EN VARCHAR(255),
  TERMINAL_ID VARCHAR(255) NOT NULL,
  CLIENT_ID VARCHAR(255) NOT NULL,
  WALLET_SHOP_ID VARCHAR(40) NOT NULL,
  INSERT_DATE DATETIME NOT NULL,
  INSERT_USER_ID VARCHAR(32) NOT NULL,
  UPDATE_DATE DATETIME,
  UPDATE_USER_ID VARCHAR(32),
  VERSION_NO DECIMAL(9) NOT NULL,
  LOGICAL_DELETE_FLAG DECIMAL(1) NOT NULL
);
