CREATE TABLE CUSTOMER (
  CUSTOMER_ID CHAR(32) NOT NULL,
  CUSTOMER_NUMBER CHAR(10),
  WALLET_ID VARCHAR(255),
  INSERT_DATE DATETIME NOT NULL,
  INSERT_USER_ID VARCHAR(32) NOT NULL,
  UPDATE_DATE DATETIME,
  UPDATE_USER_ID VARCHAR(32),
  VERSION_NO DECIMAL(9) NOT NULL,
  LOGICAL_DELETE_FLAG DECIMAL(1) NOT NULL
);
