CREATE TABLE READ_MODEL_UPDATER_OFFSET (
  TAG_NAME VARCHAR(64) NOT NULL,
  OFFSET_UUID VARCHAR(36) NOT NULL,
  INSERT_DATE DATETIME NOT NULL,
  INSERT_USER_ID VARCHAR(32) NOT NULL,
  UPDATE_DATE DATETIME,
  UPDATE_USER_ID VARCHAR(32),
  VERSION_NO DECIMAL(9) NOT NULL,
  LOGICAL_DELETE_FLAG DECIMAL(1) NOT NULL
);
