CREATE TABLE ISSUING_SERVICE (
  CONTRACT_NUMBER CHAR(10) NOT NULL,
  HOUSE_PAN VARCHAR(16),
  SERVICE_RELATION_ID DECIMAL DEFAULT NULL,
  DIGIT_4BYTE CHAR(4),
  INSERT_DATE DATETIME NOT NULL,
  INSERT_USER_ID VARCHAR(32) NOT NULL,
  UPDATE_DATE DATETIME,
  UPDATE_USER_ID VARCHAR(32),
  VERSION_NO DECIMAL(9) NOT NULL,
  LOGICAL_DELETE_FLAG DECIMAL(1) NOT NULL
);
