name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  lerna.enable.discipline: true

jobs:
  test:

    runs-on: ubuntu-latest

    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # https://www.scala-sbt.org/1.x/docs/GitHub-Actions-with-sbt.html#Caching
      - name: Coursier cache
        uses: coursier/cache-action@v5

      # https://github.com/marketplace/actions/docker-layer-caching
      - name: Pull the latest docker image
        run: docker-compose pull
      - name: Docker layer cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build the docker-compose stack
        run: docker-compose up -d

      - name: Check code format
        run: sbt scalafmtSbtCheck scalafmtCheckAll

      - name: Run tests
        run: sbt clean test:compile test

        # https://www.scala-sbt.org/1.x/docs/GitHub-Actions-with-sbt.html#Caching
      - name: Clean files for caching
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
